[package]
name = "waffledb-distributed"
version.workspace = true
edition.workspace = true

[dependencies]
waffledb-core = { path = "../waffledb-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
